import "@/styles/app.css";
import { App } from "antd";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <App>{children}</App>
    </>
  );
}
